# API REST:
# - POST /{federationContextId}/application/lcm
#     Instantiates an application on a partner OP zone.
# - GET  /{federationContextId}/application/lcm/app/{appId}/instance/{appInstanceId}/zone/{zoneId}
#     Retrieves an application instance details from partner OP.
# - DELETE  /{federationContextId}/application/lcm/app/{appId}/instance/{appInstanceId}/zone/{zoneId}
#     Terminate an application instance on a partner OP zone.
# - GET /{federationContextId}/application/lcm/app/{appId}/appProvider/{appProviderId}
#     Retrieves all application instance of partner OP

apiVersion: apiextensions.k8s.io/v1 
kind: CustomResourceDefinition
metadata:
  name: applicationdeploymentmanagement.federation.com
spec:
  group: federation.com
  names:
    kind: ApplicationDeploymentManagement
    plural: applicationdeploymentmanagement
    singular: applicationdeploymentmanagement
    shortNames:
      - app-dep-man
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [federationContextId]
              properties:
                federationContextId:
                  type: string
                  pattern: ^[A-Za-z0-9][A-Za-z0-9-]*$
                  description: This identifier shall be provided by the partner OP on successful verification and validation of the federation create request and is used by partner op to identify this newly created federation context. Originating OP shall provide this identifier in any subsequent request towards the partner op.
                transactionId:
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request
                  format: uuid
                  type: string
                appId:
                  type: string
                  pattern: ^[A-Za-z][A-Za-z0-9_]{7,63}$
                  description: Identifier used to refer to an application.
                appInstanceId:
                  type: string
                  pattern: ^[A-Za-z0-9][A-Za-z0-9_]{6,62}[A-Za-z0-9]$
                  description: Unique identifier generated by the partner OP to identify an instance of the application on a specific zone.
                zoneId:
                  type: string
                  pattern: ^[A-Za-z0-9][A-Za-z0-9-]*$
                  description: Human readable name of the zone.
                appProviderId:
                  type: string
                  pattern: ^[A-Za-z][A-Za-z0-9_]{7,63}$
                  description: UserId of the app provider.  Identifier is relevant only in context of this federation.
                appDetails:
                  type: object
                  properties:
                    appVersion:
                      type: string
                      description: Version info of the application
                    zoneInfo:
                      type: object
                      properties:
                        flavourId:
                          type: string
                          description: An identifier to refer to a specific combination of compute resources
                        resourceConsumption:
                          type: string
                          enum: [RESERVED_RES_SHALL,RESERVED_RES_PREFER,RESERVED_RES_AVOID,RESERVED_RES_FORBID] 
                          default: RESERVED_RES_AVOID
                          description: Specifies if the application can be instantiated using pre-reserved resource or not.  App provider can pre-reserve a pool of compute resource on each zone.  'RESERVED_RES_SHALL' instruct OP to use only the pre-reserved resources. 'RESERVED_RES_PREFER' instruct to first try using pre-reserved resource, if none available go for non-reserved resources. 'RESERVED_RES_AVOID' instruct OP not to use pre-reserved resource if possible, it is a choice depending upon circumstances 'RESERVED_RES_FORBID' instruct OP not to use pre-reserved resources.
                        resPool:
                          type: string
                          pattern: ^[A-Za-z0-9][A-Za-z0-9_]{6,30}[A-Za-z0-9]$
                          description: Resource pool to be used for application instantiation on this zone.  Valid only if IE 'resourceConsumption' is set to 'RESERVED_RES_SHALL' or 'RESERVED_RES_PREFER'
                    appInstCallbackLink:
                      type: string
            status:
              type: object
              properties:
                accessPointInfo:
                    type: array
                    description: Information about the IP and Port exposed by the OP. Application clients shall use these access points to reach this application instance
                    items:
                      type: object
                      required: [interfaceId,accessPoints]
                      properties:
                        interfaceId:
                          type: string
                          pattern: ^[A-Za-z0-9][A-Za-z0-9_]{6,30}[A-Za-z0-9]$
                          description: This is the interface identifier that app provider defines when application is onboarded.
                        accessPoints:
                          type: object
                          required: [port]
                          anyOf:
                            - required:
                                - fqdn
                            - required:
                                - ipv4Addresses
                            - required:
                                - ipv6Addresses
                          properties:
                            port:
                              type: integer
                              minimum: 0
                            fqdn:
                              type: string
                              description: DNS FQDN assigned to application instances in an availability zone. User Clients can resolve the FQDN to communicate with the edge instances of the application
                            ipv4Addresses:
                              type: array
                              items:
                                type: string
                                pattern: ^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$
                              minItems: 1
                            ipv6Addresses:
                              type: array
                              items:
                                type: string
                                allOf:
                                  - pattern: ^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))$
                                  - pattern: ^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))$
                              minItems: 1
                    minItems: 1
                appInstanceInfo:
                  type: array
                  items:
                    type: object
                    required: [appInstIdentifier,appInstanceState]
                    properties:
                      appInstIdentifier:
                        type: string
                        pattern: ^[A-Za-z0-9][A-Za-z0-9_]{6,62}[A-Za-z0-9]$
                        description: Unique identifier generated by the partner OP to identify an instance of the application on a specific zone.
                      appInstanceState:
                        type: string
                        enum: [PENDING,READY,FAILED,TERMINATING]
                        description: Running status of the application instance.
                  minItems: 1

