# API REST:
# - GET /partner
#     Creates one direction federation with partner operator platform.
# - GET /{federationContextId}/partner
#     Retrieves details about the federation context with the partner OP. The response shall provide info about the zones offered by the partner, partner OP network codes, information about edge discovery and LCM service etc.
# - PATCH /{federationContextId}/partner
#     API used by the Originating OP towards the partner OP, to update the parameters associated to the existing federation
# - DELETE /{federationContextId}/partner
#     Remove existing federation with the partner OP
# - GET /fed-context-id
#     Retrieves the existing federationContextId with partner operator platform.
# - GET /{federationContextId}/health
#     Retrieves health status of the federation context with the Partner OP.
# - POST /{federationContextId}/renew
#     API used by the Originating OP to renew the existing federation
# - GET /{federationContextId}/platform-caps
#     Retrieves details about OP capabilities of the federated partnes
# - GET /{federationContextId}/partner/serive/{serviceType}
#     Retrieves the list of Service APIs and associated information that a partner OP supports
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: federationmanagement.federation.com
spec:
  group: federation.com
  names:
    kind: FederationManagement
    plural: federationmanagement
    singular: federationmanagement
    shortNames:
      - fed-man
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources: #Allows the controller to update status
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                federationData:
                  type: object
                  required: [initialDate,partnerStatusLink]
                  properties:
                    origOPFederationId:
                      type: string
                      pattern: ^[A-Za-z0-9][A-Za-z0-9-]*$
                      description: Globally unique identifier allocated to an operator platform. This is valid and used only in context of MEC federation interface.
                    origOPCountryCode:
                      type: string
                      description: ISO 3166-1 Alpha-2 code for the country of Partner operator
                      pattern: ^[A-Z]{2}$
                    initialDate:
                      type: string
                      format: date-time
                      description: Time zone info of the federation initiated by the originating OP
                    partnerStatusLink:
                      type: string
                updateData:
                  type: object
                  properties:
                    objectType:
                      type: string
                      enum: [MOBILE_NETWORK_CODES,FIXED_NETWORK_CODES,OPS_POLICY,APP_POLICY]
                    operationType:
                      type: string
                      enum: [ADD_CODES,REMOVE_CODES,UPDATE_CODES,ADD_POLICY,REMOVE_POLICY,UPDATE_POLICY]
                    assocAppPolicies:
                      type: object
                      required: [policyId,appIdList]
                      properties:
                        policyId:
                          type: string
                          pattern: ^[A-Za-z][A-Za-z0-9_]{7,63}$
                          description: (ApplPolicyIdentifier) Application-level Policy unique identifier
                        appIdList:
                          description: AppIdLocList
                          type: object
                          required: [appId,appProvId]
                          properties:
                            appId:
                              type: string
                              pattern: ^[A-Za-z][A-Za-z0-9_]{7,63}$
                              description: (AppIdentifier) Identifier used to refer to an application.
                            appProvId:
                              type: string
                              pattern: ^[A-Za-z][A-Za-z0-9_]{7,63}$
                              description: (AppProviderId) UserId of the app provider.  Identifier is relevant only in context of this federation.
                            zoneIds:
                              type: array
                              minItems: 1
                              items:
                                type: string
                                pattern: ^[A-Za-z0-9][A-Za-z0-9-]*$
                                description: (ZoneIdentifier) Human readable name of the zone.
                    assocOpsPolicies:
                      type: object
                      required: [policyId,appIdList]
                      properties:
                        policyId:
                          type: string
                          pattern: ^[A-Za-z][A-Za-z0-9_]{7,63}$
                          description: (ApplPolicyIdentifier) Application-level Policy unique identifier
                        appIdList:
                          description: AppIdLocList
                          type: object
                          required: [appId,appProvId]
                          properties:
                            appId:
                              type: string
                              pattern: ^[A-Za-z][A-Za-z0-9_]{7,63}$
                              description: (AppIdentifier) Identifier used to refer to an application.
                            appProvId:
                              type: string
                              pattern: ^[A-Za-z][A-Za-z0-9_]{7,63}$
                              description: (AppProviderId) UserId of the app provider.  Identifier is relevant only in context of this federation.
                            zoneIds:
                              type: array
                              minItems: 1
                              items:
                                type: string
                                pattern: ^[A-Za-z0-9][A-Za-z0-9-]*$
                                description: (ZoneIdentifier) Human readable name of the zone.
                    modificationDate:
                      type: string
                      format: date-time
                      description: Date and time of the federation modification by the originating partner OP
                mobileNetworkIds:
                  type: object
                  properties:
                    mcc:
                      type: string
                      pattern: ^\d{3}$
                    mncs:
                      type: array
                      minItems: 1
                      items:
                        type: string
                        pattern: ^\d{2,3}$
                fixedNetworkIds:
                  type: array
                  minItems: 1
                  items:
                    type: string
                    description: List of network identifier associated with the fixedline network of the operator platform.
                capType:
                  type: string
                  description: The enumerated list of network capabilities that an OP can use for various services via SBI-NR.
                  enum: [NW_CAP_CONN_STATE_CHANGE,NW_CAP_LOCATION_RETRIEVAL,NW_CAP_USERPLANE_MGMT_EVENTS,NW_CAP_DYNAMIC_QOS]
            status:
              type: object
              properties:
                federationContextId:
                  type: string
                  pattern: ^[A-Za-z0-9][A-Za-z0-9-]*$
                  description: This identifier shall be provided by the partner OP on successful verification and validation of the federation create request and is used by partner op to identify this newly created federation context. Originating OP shall provide this identifier in any subsequent request towards the partner op.
                partnerOPFederationId:
                  type: string
                  pattern: ^[A-Za-z0-9][A-Za-z0-9-]*$
                  description: (FederationIdentifier) Globally unique identifier allocated to an operator platform. This is valid and used only in context of MEC federation interface.
                partnerOPCountryCode:
                  type: string
                  description: (CountryCode) ISO 3166-1 Alpha-2 code for the country of Partner operator
                  pattern: ^[A-Z]{2}$
                serviceEndpoint:
                  description: Service Endpoint
                  type: object
                  required: [endpointType,port]
                  anyOf:
                    - required: [fqdn]
                    - required: [ipv4Addresses]
                    - required: [ipv6Addresses]
                  properties:
                    endpointType:
                      type: string
                      enum: [edge,lcm]
                    port:
                      type: integer
                      minimum: 0
                    fqdn:
                      type: string
                      description: (EdgeAppFQDN) DNS FQDN assigned to application instances in an availability zone. User Clients can resolve the FQDN to communicate with the edge instances of the application
                    ipv4Addresses:
                      type: array
                      minItems: 1
                      items:
                        type: string
                        pattern: ^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$
                        example: 198.51.100.1
                    ipv6Addresses:
                      type: array
                      minItems: 1
                      items:
                        type: string
                        allOf:
                          - pattern: ^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))$
                          - pattern: ^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))$
                        example: 2001:db8:85a3::8a2e:370:7334
                mobileNetworkIds:
                  description: MobileNetworkIds
                  type: object
                  properties:
                    mcc:
                      type: string
                      pattern: ^\d{3}$
                    mncs:
                      type: array
                      minItems: 1
                      items:
                        type: string
                        pattern: ^\d{2,3}$
                fixedNetworkIds:
                  type: array
                  minItems: 1
                  items:
                    type: string
                  description: (FixedNetworkIds) List of network identifier associated with the fixed line network of the operator platform.
                zoneDetails:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    required: [zoneId,geographyDetails]
                    properties:
                      type: object
                      zoneId:
                        type: string
                        pattern: ^[A-Za-z0-9][A-Za-z0-9-]*$
                        description: Human readable name of the zone.
                      geolocation:
                        type: string
                        description: Latitude,Longitude as decimal fraction up to 4 digit precision
                        pattern: ^([-+]?)([\d]{1,2})((((\.)([\d]{1,4}))?(,)))(([-+]?)([\d]{1,3})((\.)([\d]{1,4}))?)$
                      geographyDetails:
                        type: string
                        description: Details about cities or state covered by the edge. Details about the type of locality for eg rural, urban, industrial etc. This information is defined in human readable form.
                platformCaps:
                  type: array
                  items:
                    type: string
                    enum: [homeRouting,Anchoring,serviceAPIs,faultMgmt,eventMgmt,resourceMonitor,networkEventMgmt,appNotificationMgmt,appLevelPolicyMgmt,opsLevelPolicyMgmt]
                  description: Home routing - Operator platform is capable of routing edge application data traffic from its edges to user device in their home location. This is the case where user devices are served in their home region (requesting platform region, non-roaming) but the corresponding edge application are in operator platform edges. Anchoring - Operator platform is capable of routing edge application traffic for roaming user devices to edge application in user device home network. Service APIs - Capability to handle Service APIs (e.g., CAMARA APIs) from the Leading OP
                federationExpiryDate:
                  type: string
                  format: date-time
                  description: Date and Time zone info of the existing federation expiry
                federationRenewalDate:
                  type: string
                  format: date-time
                  description: Date and Time zone info of the existing federation renewal. Shall be less than federationExpiryDate
                federationHealthInfo:
                  type: object
                  required: [status,dateAndTimeZoneObject,numOfAcceptedZones]
                  properties:
                    status:
                      type: object
                      required: [alarmState]
                      properties:
                        alarmState:
                          type: string
                          enum: [RAISED,UPDATED,CLEAR]
                          description: Defines the alarm state during its life cycle (raised | updated | cleared). 
                    dateAndTimeZoneObject:
                      type: string
                      format: date-time
                      description: Date and Time zone info format
                    numOfAcceptedZones:
                      type: string
                    numOfActiveAlarms:
                      type: string
                    numOfApplications:
                      type: string
                caps:
                  type: object
                  required: [capabilityId,maxiDetectionTime,locationType,maxUserPlaneLatency,supportedQoS]
                  properties:
                    capabilityId:
                      type: string
                      enum: [NW_CAP_CONN_STATE_CHANGE,NW_CAP_LOCATION_RETRIEVAL,NW_CAP_USERPLANE_MGMT_EVENTS,NW_CAP_DYNAMIC_QOS]
                      description: The enumerated list of network capabilities that an OP can use for various services via SBI-NR.
                    maxiDetectionTime:
                      type: string
                      description:  The maximum detection time in seconds that the OP can determine the UE change of connectivity with the mobile network.
                    locationType:
                      type: string
                      enum: [CELL_LEVEL_ACCURACY,REGISTRATION_AREA_ACCURACY,TRACKING_AREA_ACCURACY,GEO_LOCATION_ACCURACY]
                      description:  The enumerated list of UE location accuracy that an OP can determine via SBI-NR.
                    locationAccuracy:
                      type: string
                      enum: [LAST_KNOWN_LOCATION,CURRENT_LOCATION,INITIAL_LOCATION]
                      description:  The enumerated list of type of network location of an UE that an OP can determine via SBI-NR.
                    maxUserPlaneLatency:
                      type: string
                      description: Indicates the maximum user plane latency in units of milliseconds to decide whether edge relocation is needed to ascertain latency remain in this range.
                    supportedQoS:
                      type: string
                      description:  Set of one or more 5G QoS Identifier (5QI or 4G QCI) created via concatanation of Resource Type and 5QI values i.e., GBR1, GBR2, GBR65, NONGBR79 etc.
                service:
                  type: object
                  properties:
                    serviceCaps:
                      type: array
                      minItems: 1
                      items:
                        type: string
                        enum: [QualityOnDemand,DeviceLocation,DeviceStatus,SimSwap,NumberVerification,DeviceIdentifier]
                      description: (serviceAPINames) List of Service API capability names an OP supports and offers to other OPs "quality_on_demand", "device_location" etc.
                    serviceType:
                      type: string
                      enum: ["api_federation"]
                      description: An identifier to refer to partner OP capabilities for application providers.
                    apiRoutingInfo:
                      type: array
                      minItems: 1
                      items:
                        type: string
                        pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))?$
                      description: (serviceRoutingInfo) List of public IP addresses MNO manages for UEs to connect with public data networks

