 # API REST:
# - GET /federation-resources
#     Retrieves REST APIs supported by an OP for federation services
# Translate it in:
#     Retrieves the status K8s API supported by an OP for federation services

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: federationapimanagement.federation.com
spec:
  group: federation.com
  names:
    kind: FederationAPIManagement
    plural: federationapimanagement
    singular: federationapimanagement
    shortNames:
      - fed-api-man
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
       status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                federationContextId:
                  type: string
                  pattern: ^[A-Za-z0-9][A-Za-z0-9-]*$
                  description: This identifier shall be provided by the partner OP on successful verification and validation of the federation create request and is used by partner op to identify this newly created federation context. Originating OP shall provide this identifier in any subsequent request towards the partner op.
            status:
              type: object
              properties:
                api:
                  type: object
                  required: [federationmanagement]
                  properties:
                    federationmanagement: #(plural of CRD)
                      type: object
                      properties:
                        k8sOperations:
                          type: object
                          required: [href,version,group,plural]
                          properties:
                            href:
                              type: string
                            version:
                              type: string
                            group:
                              type: string
                            plural:
                              type: string
                        apiOperations: ##We decided to leave it in to maintain consistency with the GSMA REST API
                          type: array
                          description: List of endpoints for the given API category
                          minItems: 1
                          items:
                            type: object
                            required: [href,httpMethods]
                            properties:
                              href:
                                type: string
                              httpMethods:
                                type: array
                                description: List of HTTP Methods supported for the given API category
                                minItems: 1
                                items:
                                  type: string
                    availabilityzone:
                      type: object
                      properties:
                        k8sOperations:
                          type: object
                          required: [href,version,group,plural]
                          properties:
                            href:
                              type: string
                            version:
                              type: string
                            group:
                              type: string
                            plural:
                              type: string
                        apiOperations: #restOperations
                          type: array
                          description: List of endpoints for the given API category
                          minItems: 1
                          items:
                            type: object
                            required: [href,httpMethods]
                            properties:
                              href:
                                type: string
                              httpMethods:
                                type: array
                                description: List of HTTP Methods supported for the given API category
                                minItems: 1
                                items:
                                  type: string
                    artefactmanagement:
                      type: object
                      properties:
                        k8sOperations:
                          type: object
                          required: [href,version,group,plural]
                          properties:
                            href:
                              type: string
                            version:
                              type: string
                            group:
                              type: string
                            plural:
                              type: string
                        apiOperations: #restOperations
                          type: array
                          description: List of endpoints for the given API category
                          minItems: 1
                          items:
                            type: object
                            required: [href,httpMethods]
                            properties:
                              href:
                                type: string
                              httpMethods:
                                type: array
                                description: List of HTTP Methods supported for the given API category
                                minItems: 1
                                items:
                                  type: string               
                    filemanagement:
                      type: object
                      properties:
                        k8sOperations:
                          type: object
                          required: [href,version,group,plural]
                          properties:
                            href:
                              type: string
                            version:
                              type: string
                            group:
                              type: string
                            plural:
                              type: string
                        apiOperations: #restOperations
                          type: array
                          description: List of endpoints for the given API category
                          minItems: 1
                          items:
                            type: object
                            required: [href,httpMethods]
                            properties:
                              href:
                                type: string
                              httpMethods:
                                type: array
                                description: List of HTTP Methods supported for the given API category
                                minItems: 1
                                items:
                                  type: string
                    onboardingmanagement:
                      type: object
                      properties:
                        k8sOperations:
                          type: object
                          required: [href,version,group,plural]
                          properties:
                            href:
                              type: string
                            version:
                              type: string
                            group:
                              type: string
                            plural:
                              type: string
                        apiOperations: #restOperations
                          type: array
                          description: List of endpoints for the given API category
                          minItems: 1
                          items:
                            type: object
                            required: [href,httpMethods]
                            properties:
                              href:
                                type: string
                              httpMethods:
                                type: array
                                description: List of HTTP Methods supported for the given API category
                                minItems: 1
                                items:
                                  type: string
                    deploymentmanagement:
                      type: object
                      properties:
                        k8sOperations:
                          type: object
                          required: [href,version,group,plural]
                          properties:
                            href:
                              type: string
                            version:
                              type: string
                            group:
                              type: string
                            plural:
                              type: string
                        apiOperations: #restOperations
                          type: array
                          description: List of endpoints for the given API category
                          minItems: 1
                          items:
                            type: object
                            required: [href,httpMethods]
                            properties:
                              href:
                                type: string
                              httpMethods:
                                type: array
                                description: List of HTTP Methods supported for the given API category
                                minItems: 1
                                items:
                                  type: string
                    #in future
                      #resourceManagement:
                      #edgeNodeSharing:
                      #serviceManagement:
                      #reportingManagement:
                      #eventManagementAPI:
                      #alarmManagement:
                      #networkEventManagement:
                      #appEventManagement:
                      #appPolicyManagement:
                      #opPolicyManagment:
                state:
                  type: string
                  description: Current state of the artefact upload
                  enum: [Pending,Uploading,Uploaded,Failed]
                message:
                  type: string
                  description: message indicating details about the current state
                lastUpdated:
                  type: string
                  format: date-time
                  description: Timestamp of the last status update
