# API REST:
# - POST /{federationContextId}/application/onboarding
#     Submits an application details to a partner OP. Based on the details provided,  partner OP shall do bookkeeping, resource validation and other pre-deployment operations.
# - GET /{federationContextId}/application/onboarding/app/{appId}
#     Retrieves application details from partner OP
# - DELETE /{federationContextId}/application/onboarding/app/{appId}
#     Deboards the application from all zones, if any, and deletes the App.
# - PATCH /{federationContextId}/application/onboarding/app/{appId}
#     Updates partner OP about changes in application compute resource requirements, QOS Profile, associated descriptor or change in associated components
# - GET /{federationContextId}/application/onboarding/app/{appId}/zone/{zoneId}
#     Retrieves application details from partner OP
# - DELETE /{federationContextId}/application/onboarding/app/{appId}/zone/{zoneId}
#     Deboards an application from specific partner OP zones
# - POST /{federationContextId}/application/onboarding/app/{appId}/additionalZones
#     Onboards an existing application to a new zone within partner OP.
# - POST /{federationContextId}/application/onboarding/app/{appId}/zoneForbid
#     Forbid/allow application instantiation on a partner zone
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applicationonboardingmanagement.federation.com
spec:
  group: federation.com
  names:
    kind: ApplicationOnboardingManagement
    plural: applicationonboardingmanagement
    singular: applicationonboardingmanagement
    shortNames:
      - app-onboard-man
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [federationContextId, appInfo]
              properties:
                federationContextId:
                  type: string
                  pattern: ^[A-Za-z0-9][A-Za-z0-9-]*$
                  description: This identifier shall be provided by the partner OP on successful verification and validation of the federation create request and is used by partner op to identify this newly created federation context. Originating OP shall provide this identifier in any subsequent request towards the partner op.               
                zoneSettings:
                  type: array
                  items:
                    type: object
                    properties:
                      zoneId:
                        type: array
                        minItems: 1
                        items:
                          type: string
                          pattern: ^[A-Za-z0-9][A-Za-z0-9-]*$
                          description: Human readable name of the zone.
                      forbid:
                        type: boolean
                        description: Value 'true' will forbid application instantiation on this zone.  No new instance of the application can be created on this zone.
                  minItems: 1
                appInfo:
                  description: Details about application compute resource requirements, associated artefacts, QoS profile and regions where application shall be made available etc.
                  type: object
                  required: [appId]
                  properties:
                    appId:
                      type: string
                      pattern: ^[A-Za-z][A-Za-z0-9_]{7,63}$
                      description: Identifier used to refer to an application.
                    appProviderId:
                      type: string
                      pattern: ^[A-Za-z][A-Za-z0-9_]{7,63}$
                      description: UserId of the app provider.  Identifier is relevant only in context of this federation.
                    appDeploymentZones:
                      description: Details about partner OP zones where the application should be made available;  This field when specified will instruct the OP to restrict application instantiation only on the listed zones.
                      type: array
                      items:
                        type: object
                        properties:
                          zoneId:
                            type: string
                            pattern: ^[A-Za-z0-9][A-Za-z0-9-]*$
                            description: Human readable name of the zone.
                          countryCode:
                            type: string
                            description: ISO 3166-1 Alpha-2 code for the country of Partner operator
                            pattern: ^[A-Z]{2}$
                      minItems: 1
                    appMetaData:
                      type: object
                      description: Application metadata details
                      required: [appName,version,accessToken]
                      properties:
                        appName:
                          type: string
                          pattern: ^[A-Za-z][A-Za-z0-9_]{7,31}$
                          description: Name of the application. Application provider define a human readable name for the application
                        version:
                          type: string
                          description: Version info of the application
                        appDescription:
                          type: string
                          minLength: 16
                          maxLength: 256
                          description: Brief application description provided by application provider
                        mobilitySupport:
                          type: boolean
                          default: false
                          description: Indicates if an application is sensitive to user mobility and can be relocated. Default is “FALSE”
                        accessToken:
                          type: string
                          description: An application Access key, to be used with UNI interface to authorize UCs Access to a given application
                        category:
                          type: string
                          enum: [IOT,HEALTH_CARE,GAMING,VIRTUAL_REALITY,SOCIALIZING,SURVEILLANCE,ENTERTAINMENT,CONNECTIVITY,PRODUCTIVITY,SECURITY,INDUSTRIAL,EDUCATION,OTHERS]
                          description: Possible categorization of the application
                    appQoSProfile:
                      description: Parameters corresponding to the performance constraints, tenancy details etc.
                      type: object
                      required: [latencyConstraints]
                      properties:
                        latencyConstraints:
                          type: string
                          enum: [NONE,LOW,ULTRALOW]
                          description: Latency requirements for the application.Allowed values (non-standardized) are none, low and ultra-low. Ultra-Low may corresponds to range 15 - 30 msec, Low correspond to range 30 - 50 msec. None means 51 and above
                        bandwidthRequired:
                          type: integer
                          format: int32
                          minimum: 1
                          description: Data transfer bandwidth requirement (minimum limit) for the application. It should in Mbits/sec
                        multiUserClients:
                          type: string
                          enum: [APP_TYPE_SINGLE_USER,APP_TYPE_MULTI_USER]
                          description: Single user type application are designed to serve just one client. Multi user type application is designed to serve multiple clients
                        noOfUsersPerAppInst:
                          type: integer
                          default: 1
                          description: Maximum no of clients that can connect to an instance of this application. This parameter is relevant only for application of type multi user
                        appProvisioning:
                          type: boolean
                          default: true
                          description: Define if application can be instantiated or not
                    appComponentSpecs:
                      type: array
                      minItems: 1
                      items:
                        type: object
                        properties:
                          serviceNameNB:
                            type: string
                            pattern: ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9])\.)*([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9])$
                            description: Must be a valid RFC 1035 label name. This defines the DNS name via which the component can be accessed over NBI. Access via     serviceNameNB is restricted on specific ports. Platform shall expose component access externally via this DNS name
                          serviceNameEW:
                            type: string
                            pattern: ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9])\.)*([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9])$
                            description: Must be a valid RFC 1035 label name. This defines the DNS name via which the component can be accessed via peer components. Access via serviceNameEW is open on all ports.   Platform shall not expose serviceNameEW externally outside edge.
                          componentName:
                            type: string
                            pattern: ^[A-Za-z0-9][A-Za-z0-9_]{6,62}[A-Za-z0-9]$
                            # Possible error in description.
                            description: Must be a valid RFC 1035 label name.  Component name must be unique with an application
                          artefactId:
                            type: string
                            format: uuid
                            description: A globally unique identifier associated with the artefact. Originating OP generates this identifier when artefact is submitted over NBI.
                    appStatusCallbackLink:
                      type: string
                    edgeAppFQDN:
                      type: string
                      description: DNS FQDN assigned to application instances in an availability zone. User Clients can resolve the FQDN to communicate with the edge instances of the application
                    onboardStatusInfo:
                      type: string
                      enum: [PENDING,ONBOARDED,DEBOARDING,REMOVED,FAILED]
                      description: Defines change in application status. This change could be related to application itself or an application instance status
            status:
              type: object
              properties:
                state:
                  type: string
                  description: Current state of the artefact upload
                  enum: [Pending,Uploading,Uploaded,Failed]
                message:
                  type: string
                  description: message indicating details about the current state
                lastUpdated:
                  type: string
                  format: date-time
                  description: Timestamp of the last status update
